### PR TITLE
Changed Edmond Karp to use array data structure instead of a map to store information about augmenting paths for backtracking the path for speed

### PR DESCRIPTION
**Pull request by juliuskoskela**
-	I changed swapped the map data structure successfully and gained about 1 sec
	increase with gen_superposition_4 and about 2s with gen_superposition_3. So
	50 - 100% increase.  Some notes about why the map was not a good idea. We
	should use maps if these requirements are met:
	
	1. We want to index data fast when we know the key.
	2. We rarely insert, but often retrieve data.

	In the old case, the 2nd requirement was not met. We were adding a lot of
	data to a map in a loop and then searching for it resulting in overhead with
	hashing.
	
-	I implemented a fast test to store unique node IDs using a global variable
	and storing that variable in the value of a node attribute. The idea was
	that comapring the values is faster than comapring the strings. This
	resultes in a net speed decrease though. I suspect this could be because of
	the cache miss when casting the node attribute. The only way to avoid this
	is to store the id value in the node struct itself. This would probably get
	us at least a small speed increase. I left the implementaion there and use
	it in update_edge_flows as example. However if you switch arr_find_by (line
	86) with the above lem_find_node function. We can probably ditch this idea
	although s_cmp takes a lot of time in perf test.
	
-	I changed the libraries so that now all allocations when creating or growing
	any of the data-structures will exit the program. Now there can be no side
	effects from any of these functions so we can remove all if statemets
	checking for null arrays, maps etc. This will dramatically reduce
	conditional statements and memcmps in the program and could also help the
	optimizer.
	
Some further ideas and to-do's:

-	Let's try to move all allocations to the level where the variable is
	declared.
	
-	For clarity, we could use implementation level typedefs for core.h
	datatypes such as:
	
	```c
	typedef t_array t_edges;
	typedef	t_array	t_nodes;
	typedef	t_array	t_path; // Same as nodes but different context
	typedef	t_array	t_routes // Array of paths
	typedef	t_array	t_network // Array of routes
	```
	
	Or something like that. The nesting with the path combinations is a bit
	confusing so typedeffing could make a lot of things more readable. Also when
	the type is defined, we can use shorter names in source code.
	
-	As extension to the above, we should improve naming and making it concise
	across the board. I suggest we prefix all implementation functions with the
	prefix "lem_". This makes it easier to search for the relevant functions in
	files and in the editor.

-	Get rid of t_coordinates struct and add the coordinates as values straight
	to the attr struct.

-	I suggest we make macros for debug printing (didn't implement this yet).
	
	```c
	#define DEBUG_PRINT_EDGES print_method
	
	void	print_method(char *str)
	{
		// Print the thing.
	}
	```
	
	This way the debug prints will be capitalized and easier to find in source
	code.

-	Make a performance profiling with the MAC tool.
	
Ok I'll stop here :D Great work! We are getting super fast!!!

### CODE REVIEW

**Comment by satukoskinen** [comment]
> I changed swapped the map data structure successfully and gained about 1 sec
> increase with gen_superposition_4 and about 2s with gen_superposition_3. So
> 50 - 100% increase.

I pulled the branch, updated the core and compiled it. For some reason, on my computer it performs worse than on the master branch:

```
➜  lem_in git:(julius) ✗ time ./lem_in < test/gen_superposition_4 > output
./lem_in < test/gen_superposition_4 > output  2.39s user 0.29s system 88% cpu 3.038 total
➜  lem_in git:(julius) ✗ time ./lem_in < test/gen_superposition_3 > output
./lem_in < test/gen_superposition_3 > output  4.01s user 0.45s system 99% cpu 4.500 total
➜  lem_in git:(julius) ✗ time ./lem_in < test/gen_superposition_2 > output
./lem_in < test/gen_superposition_2 > output  5.66s user 0.53s system 99% cpu 6.219 total
➜  lem_in git:(julius) ✗ time ./lem_in < test/gen_superposition_1 > output
./lem_in < test/gen_superposition_1 > output  1.10s user 0.16s system 99% cpu 1.260 total
```

vs.

```
➜  lem_in git:(master) ✗ time ./lem_in < test/gen_superposition_4 > output
./lem_in < test/gen_superposition_4 > output  1.40s user 0.05s system 78% cpu 1.845 total
➜  lem_in git:(master) ✗ time ./lem_in < test/gen_superposition_3 > output
./lem_in < test/gen_superposition_3 > output  2.30s user 0.06s system 99% cpu 2.360 total
➜  lem_in git:(master) ✗ time ./lem_in < test/gen_superposition_2 > output
./lem_in < test/gen_superposition_2 > output  3.23s user 0.06s system 99% cpu 3.296 total
➜  lem_in git:(master) ✗ time ./lem_in < test/gen_superposition_1 > output
./lem_in < test/gen_superposition_1 > output  0.59s user 0.04s system 99% cpu 0.629 total
```

I can see if I can look into this with the Instruments tool.

> I implemented a fast test to store unique node IDs using a global variable
> and storing that variable in the value of a node attribute. The idea was
> that comapring the values is faster than comapring the strings. This
> resultes in a net speed decrease though. I suspect this could be because of
> the cache miss when casting the node attribute. The only way to avoid this
> is to store the id value in the node struct itself. This would probably get
> us at least a small speed increase.

I would say storing an integer id for internal use would be a good idea. That would also allow for creating some "helper" integer arrays where the indexes would correspond to the node ids (if they are sequential and start from 0). In many graph implementation examples these are used to create "visited" or "prev" tables, for example.

> I changed the libraries so that now all allocations when creating or growing
> any of the data-structures will exit the program

In general, I would prefer for a library function to not exit, but to return an error value and then leave it up to the caller to call exit in case of failure.

**Comment by satukoskinen** [comment]
And on the to-dos:

> Let's try to move all allocations to the level where the variable is
> declared.

I agree that this is a good principle in general, just that it does not work in practice if what is allocated is retrieved as a return value from some function. Or alternatively, then it would need to be allocated first and a pointer to it would be passed as an argument for the function that assigns the content to it.

> For clarity, we could use implementation level typedefs for core.h
> datatypes such as:
> 
> typedef t_array t_edges;
> typedef	t_array	t_nodes;
> typedef	t_array	t_path; // Same as nodes but different context
> typedef	t_array	t_routes // Array of paths
> typedef	t_array	t_network // Array of routes
> Or something like that. The nesting with the path combinations is a bit
> confusing so typedeffing could make a lot of things more readable. Also when
> the type is defined, we can use shorter names in source code.
> 
> As extension to the above, we should improve naming and making it concise
> across the board. I suggest we prefix all implementation functions with the
> prefix "lem_". This makes it easier to search for the relevant functions in
> files and in the editor.

The prefix is a good idea, we should do that. And yeah, the naming is not the best currently. We could try out the typedefs if that distinguishes the arrays better.

> Get rid of t_coordinates struct and add the coordinates as values straight
> to the attr struct.

Having them together in a struct is useful once something has to be done with the coordinates, or that's what I working for me in some other projects. But if that feels inconvenient for this one the struct can be removed.

> I suggest we make macros for debug printing (didn't implement this yet).

I agree!

**Comment by juliuskoskela** [comment]
> I pulled the branch, updated the core and compiled it. For some reason, on my computer it performs worse than on the master branch:

Hmm weird. Will test on my Mac.

> In general, I would prefer for a library function to not exit, but to return an error value and then leave it up to the caller to call exit in case of failure.

This resource states that what I suggest is the standard way of handling the situation in Linux kernel for example

https://eli.thegreenplace.net/2009/10/30/handling-out-of-memory-conditions-in-c/


The abort policy is simple and familiar: when no memory is available, print a polite error message and exit (abort) the application. This is the most commonly used policy - most command-line tools and desktop applications use it.

As a matter of fact, this policy is so common that most Unix programs use a gnulib library function xmalloc instead of malloc:

```c
void *
xmalloc (size_t n)
{
  void *p = malloc (n);
  if (!p && n != 0)
    xalloc_die ();
  return p;
}
```

> I agree that this is a good principle in general, just that it does not work in practice if what is allocated is retrieved as a return value from some function. Or alternatively, then it would need to be allocated first and a pointer to it would be passed as an argument for the function that assigns the content to it.

Yes that's what I propose. Allocate the datatype with the allocation functions from library such as arr_new and free on same level. Pass the pointer in between. If done like this it will also make object lifetime more explicit. "This is the way"

**Comment by juliuskoskela** [comment]
I tested on my Mac

Test: gen_superposition_4

Old implementation: 3.79sec
New implementation: 2.44sec

**Pull request merged**
